//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessTierBudgetUp.DatabaseClasses
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Model1Container : DbContext
    {
        public Model1Container()
            : base("name=Model1Container")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Project> Projects { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Income> Incomes { get; set; }
        public virtual DbSet<Objective> Objectives { get; set; }
        public virtual DbSet<Activity> Activities { get; set; }
        public virtual DbSet<Expense> Expenses { get; set; }
        public virtual DbSet<UPStaffMember> UPStaffMembers { get; set; }
        public virtual DbSet<Contractor> Contractors { get; set; }
        public virtual DbSet<Travel> Travels { get; set; }
        public virtual DbSet<Equipment> Equipments { get; set; }
        public virtual DbSet<Operational> Operationals { get; set; }
        public virtual DbSet<Bursary> Bursaries { get; set; }
        public virtual DbSet<BursaryType> BursaryTypes { get; set; }
        public virtual DbSet<PostLevel> PostLevels { get; set; }
        public virtual DbSet<Operation_Type> Operation_Type { get; set; }
        public virtual DbSet<AirlineExpense> AirlineExpenses { get; set; }
        public virtual DbSet<Accommodation> Accommodations { get; set; }
        public virtual DbSet<CarExpense> CarExpenses { get; set; }
        public virtual DbSet<Gautrain> Gautrains { get; set; }
        public virtual DbSet<Visa> Visas { get; set; }
        public virtual DbSet<Allowance> Allowances { get; set; }
        public virtual DbSet<UserCredentials> UserCredentials { get; set; }
        public virtual DbSet<Admin_SysSettings> Admin_SysSettings { get; set; }
        public virtual DbSet<Project_Settings> Project_Settings { get; set; }
        public virtual DbSet<Title> Titles { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<Faculty> Faculties { get; set; }
        public virtual DbSet<EmailDomains> EmailDomains { get; set; }
        public virtual DbSet<DurationType> DurationTypes { get; set; }
        public virtual DbSet<Note> Notes { get; set; }
    }
}
