//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessTierBudgetUp.DatabaseClasses
{
    using System;
    using System.Collections.Generic;
    
    public partial class Objective
    {
        public Objective()
        {
            this.Activities = new HashSet<Activity>();
        }
    
        public int Id { get; set; }
        public int ProjectId { get; set; }
        public string ObjectiveName { get; set; }
    
        public virtual Project Project { get; set; }
        public virtual ICollection<Activity> Activities { get; set; }
    }
}
