//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessTierBudgetUp.DatabaseClasses
{
    using System;
    using System.Collections.Generic;
    
    public partial class Travel
    {
        public int Id { get; set; }
        public int TravellerNo { get; set; }
        public int DurationDays { get; set; }
        public System.DateTime DepartureDate { get; set; }
        public string Destination { get; set; }
    
        public virtual Expense Expense { get; set; }
        public virtual AirlineExpense AirlineExpense { get; set; }
        public virtual Accommodation Accommodation { get; set; }
        public virtual CarExpense CarExpense { get; set; }
        public virtual Gautrain Gautrain { get; set; }
        public virtual Visa Visa { get; set; }
        public virtual Allowance Allowance { get; set; }
    }
}
