
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace BizTier
{

using System;
    using System.Collections.Generic;
    
public partial class Expens
{

    public Expens()
    {

        this.Contractors = new HashSet<Contractor>();

        this.Equipments = new HashSet<Equipment>();

        this.Operationals = new HashSet<Operational>();

        this.Travels = new HashSet<Travel>();

        this.UPStaffMembers = new HashSet<UPStaffMember>();

        this.Cars = new HashSet<Car>();

    }


    public int Id { get; set; }

    public int ActivityId { get; set; }

    public double Amount { get; set; }

    public int Note_Id { get; set; }



    public virtual Activity Activity { get; set; }

    public virtual ICollection<Contractor> Contractors { get; set; }

    public virtual ICollection<Equipment> Equipments { get; set; }

    public virtual Note Note { get; set; }

    public virtual ICollection<Operational> Operationals { get; set; }

    public virtual ICollection<Travel> Travels { get; set; }

    public virtual ICollection<UPStaffMember> UPStaffMembers { get; set; }

    public virtual ICollection<Car> Cars { get; set; }

}

}
