
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace BizTier
{

using System;
    using System.Collections.Generic;
    
public partial class Note
{

    public Note()
    {

        this.Bursaries = new HashSet<Bursary>();

        this.Expenses = new HashSet<Expens>();

        this.Incomes = new HashSet<Income>();

    }


    public int Id { get; set; }

    public string UserNote { get; set; }



    public virtual ICollection<Bursary> Bursaries { get; set; }

    public virtual ICollection<Expens> Expenses { get; set; }

    public virtual ICollection<Income> Incomes { get; set; }

}

}
