
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace BizTier
{

using System;
    using System.Collections.Generic;
    
public partial class Operation_Type
{

    public Operation_Type()
    {

        this.Operationals = new HashSet<Operational>();

    }


    public int Id { get; set; }

    public string Description { get; set; }



    public virtual ICollection<Operational> Operationals { get; set; }

}

}
