
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace BizTier
{

using System;
    using System.Collections.Generic;
    
public partial class Operational
{

    public int Id { get; set; }

    public int ExpenseId { get; set; }

    public int Operation_TypeId { get; set; }

    public int Quantity { get; set; }

    public double PricePerUnit { get; set; }

    public int Expense_Id { get; set; }



    public virtual Expens Expens { get; set; }

    public virtual Operation_Type Operation_Type { get; set; }

}

}
