
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace BizTier
{

using System;
    using System.Collections.Generic;
    
public partial class PostLevel
{

    public PostLevel()
    {

        this.UPStaffMembers = new HashSet<UPStaffMember>();

    }


    public int Id { get; set; }

    public string Description { get; set; }

    public string AnnualSalary { get; set; }



    public virtual ICollection<UPStaffMember> UPStaffMembers { get; set; }

}

}
