
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace BizTier
{

using System;
    using System.Collections.Generic;
    
public partial class Project_Settings
{

    public Project_Settings()
    {

        this.Projects = new HashSet<Project>();

    }


    public int Id { get; set; }

    public double EscalationRate { get; set; }

    public double SubventionRate { get; set; }

    public double InstitutionalCost { get; set; }

    public double UPFleetDailyRate { get; set; }

    public double FCkmRate { get; set; }



    public virtual ICollection<Project> Projects { get; set; }

}

}
