//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BizTier
{
    using System;
    using System.Collections.Generic;
    
    public partial class Travel
    {
        public Travel()
        {
            this.Accommodations = new HashSet<Accommodation>();
            this.AirlineExpenses = new HashSet<AirlineExpens>();
            this.Allowances = new HashSet<Allowance>();
            this.CarExpenses = new HashSet<CarExpens>();
            this.Gautrains = new HashSet<Gautrain>();
            this.Visas = new HashSet<Visa>();
        }
    
        public int Id { get; set; }
        public int TravellerNo { get; set; }
        public int DurationDays { get; set; }
        public System.DateTime DepartureDate { get; set; }
        public string Destination { get; set; }
        public int Expense_Id { get; set; }
    
        public virtual ICollection<Accommodation> Accommodations { get; set; }
        public virtual ICollection<AirlineExpens> AirlineExpenses { get; set; }
        public virtual ICollection<Allowance> Allowances { get; set; }
        public virtual ICollection<CarExpens> CarExpenses { get; set; }
        public virtual Expens Expens { get; set; }
        public virtual ICollection<Gautrain> Gautrains { get; set; }
        public virtual ICollection<Visa> Visas { get; set; }
    }
}
