
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace BizTier
{

using System;
    using System.Collections.Generic;
    
public partial class UPStaffMember
{

    public int Id { get; set; }

    public int PostLevelId { get; set; }

    public int DaysInvolved { get; set; }

    public bool SubventionLevy { get; set; }

    public int Expense_Id { get; set; }



    public virtual Expens Expens { get; set; }

    public virtual PostLevel PostLevel { get; set; }

}

}
