
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace BizTier
{

using System;
    using System.Collections.Generic;
    
public partial class Verification
{

    public string Email { get; set; }

    public string VericicationCode { get; set; }

    public System.DateTime DateIssues { get; set; }

    public int UserID { get; set; }

}

}
